from app.extensions import db

class PatientVisitFact(db.Model):
    __tablename__ = "Fact_PatientVisits"
    
    visit_id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    patient_id = db.Column(db.String(100), nullable=True)
    prediction_id = db.Column(db.Integer, nullable=True, index=True)
    visit_date = db.Column(db.DateTime, nullable=False, index=True)
    visit_year = db.Column(db.Integer)
    visit_month = db.Column(db.Integer)
    visit_week = db.Column(db.Integer)
    visit_day = db.Column(db.Integer)
    encounterclass = db.Column(db.String(50))
    gender = db.Column(db.String(10))
    city = db.Column(db.String(100), nullable=False, index=True)
    state = db.Column(db.String(100))
    country = db.Column(db.String(100))
    lat = db.Column(db.Float)
    lon = db.Column(db.Float)
    season = db.Column(db.String(50))
    comorbidity_count = db.Column(db.Integer)
    age_at_visit = db.Column(db.Float)
    disease = db.Column(db.String(100), nullable=False, index=True)
    visit_number = db.Column(db.Float)
    
    # Symptoms
    sym_fever = db.Column(db.Integer, default=0)
    sym_chills = db.Column(db.Integer, default=0)
    sym_headache = db.Column(db.Integer, default=0)
    sym_fatigue = db.Column(db.Integer, default=0)
    sym_vomiting = db.Column(db.Integer, default=0)
    sym_diarrhea = db.Column(db.Integer, default=0)
    sym_cough = db.Column(db.Integer, default=0)
    sym_shortness_of_breath = db.Column(db.Integer, default=0)
    sym_chest_pain = db.Column(db.Integer, default=0)
    sym_rash = db.Column(db.Integer, default=0)
    sym_muscle_pain = db.Column(db.Integer, default=0)
    sym_abdominal_pain = db.Column(db.Integer, default=0)
    sym_night_sweats = db.Column(db.Integer, default=0)
    sym_weight_loss = db.Column(db.Integer, default=0)
    sym_jaundice = db.Column(db.Integer, default=0)
    sym_stiff_neck = db.Column(db.Integer, default=0)
    sym_sensitivity_to_light = db.Column(db.Integer, default=0)
    sym_red_eyes = db.Column(db.Integer, default=0)
    sym_runny_nose = db.Column(db.Integer, default=0)
    sym_sore_throat = db.Column(db.Integer, default=0)
    sym_hemorrhage = db.Column(db.Integer, default=0)
    sym_sweating = db.Column(db.Integer, default=0)
    sym_dehydration = db.Column(db.Integer, default=0)
    sym_muscle_cramps = db.Column(db.Integer, default=0)
    sym_loss_of_smell = db.Column(db.Integer, default=0)
    sym_swollen_lymph_nodes = db.Column(db.Integer, default=0)
    sym_pain_behind_eyes = db.Column(db.Integer, default=0)
    sym_general_weakness = db.Column(db.Integer, default=0)

    is_outbreak = db.Column(db.Integer, default=0)
    hospital_name = db.Column(db.String(250))
    city_enc = db.Column(db.Integer)
    country_enc = db.Column(db.Integer)
    disease_enc = db.Column(db.Integer)
    season_enc = db.Column(db.Integer)
    gender_enc = db.Column(db.Integer)
    age_at_visit_norm = db.Column(db.Float)
    lat_norm = db.Column(db.Float)
    lon_norm = db.Column(db.Float)
    comorbidity_count_norm = db.Column(db.Float)
    day_index = db.Column(db.Float)
    day_index_norm = db.Column(db.Float)
    recent_case_count = db.Column(db.Float)
    recent_case_count_norm = db.Column(db.Float)
    
    if_pred = db.Column(db.Integer, default=0)
    if_score = db.Column(db.Float)
    
    # PCA
    pca_0 = db.Column(db.Float)
    pca_1 = db.Column(db.Float)
    pca_2 = db.Column(db.Float)
    pca_3 = db.Column(db.Float)
    pca_4 = db.Column(db.Float)
    pca_5 = db.Column(db.Float)
    pca_6 = db.Column(db.Float)
    pca_7 = db.Column(db.Float)
    
    dbscan_score = db.Column(db.Float)
    dbscan_pred = db.Column(db.Integer, default=0)
